# Generated by Django 4.1.7 on 2023-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_unittest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='max_speed',
            field=models.IntegerField(verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='owners',
            field=models.IntegerField(verbose_name='Owners'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voleybolteams',
            name='jump',
            field=models.FloatField(verbose_name='Jump'),
        ),
        migrations.AlterField(
            model_name='voleybolteams',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='voleybolteams',
            name='speed',
            field=models.IntegerField(verbose_name='Speed'),
        ),
    ]
