# Generated by Django 4.1.7 on 2023-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_unittest', '0002_alter_cars_max_speed_alter_cars_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='owners',
            field=models.CharField(max_length=250, verbose_name='Owners'),
        ),
    ]
