name: Start Djnago App

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies and run unittest
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 actions/manage.py test